### ISSUE TITLE
Argument of length 0 in get_timeseries

### ISSUE THREAD

**Issue by Nygdat** [ahmedmohamedali/eikonapir#7] opened 2017-12-18 09:54 UTC
I have seeing this error a couple of times. Usually when Im trying to download a big index like New York Stock exchange. Usually it goes well, but sometimes it throws this error. This time at stock WYN.N. 

get_timeseries("WYN.N",list("TIMESTAMP","HIGH","CLOSE","LOW","OPEN","VOLUME"),"2000-01-01T15:04:05",end_time,"daily")

[1] "WYN.N"
Error in 1:nrow(input_data_frame) : argument of length 0
Calls: get_timeseries -> get_formatted_data_frame

**Comment by nguyenbenoit** [comment] 2018-01-21 13:44
Same error fore ECBASSET series.
Using debug, I got response status 200 and apparently no data at all in the timeseries request.

 get_timeseries(list("ECBASSET="),
 fields=list("TIMESTAMP","BID"), 
 start_date = "2017-12-01T15:04:05", 
 end_date = "2017-12-30T15:04:05",
 interval="weekly",
 normalize=TRUE,
 debug=TRUE)

[1] "Request *************************************"
{"Entity":{"E":["TimeSeries"],"W":{"rics":[["ECBASSET="]],"fields":[["TIMESTAMP"],["BID"]],"interval":["weekly"],"startdate":["2017-12-01T15:04:05"],"enddate":["2017-12-30T15:04:05"]}}} 
[1] "Response *************************************"
[1] "{\"timeseriesData\":[{\"dataPoints\":[[\"2017-12-08T00:00:00Z\",null],[\"2017-12-15T00:00:00Z\",null],[\"2017-12-22T00:00:00Z\",null],[\"2017-12-29T00:00:00Z\",null]],\"fields\":[{\"name\":\"TIMESTAMP\",\"type\":\"DateTime\"},{\"name\":\"BID\",\"type\":\"\\u003cnil\\u003e\"}],\"ric\":\"ECBASSET=\",\"statusCode\":\"Normal\"}]}"
[1] "Response status *************************************"
[1] 200

**Comment by nguyenbenoit** [comment] 2018-01-21 14:05
My bad: it worked with field CLOSE (BID works only with get_data()) and normalize=FALSE

**Comment by hummali** [comment] 2018-02-23 18:45
SOLUTION: limit get_timeseries to run for 300 tickers per time and the issue is resolved. 301, and it crashes. I believe it is a reuters API limitation as it allows only 300 rows to be downloaded at one time.

**Comment by ahmedmohamedali** [comment] 2019-02-01 16:42
Closing this issue as this is not an API bug.

**Closed by ahmedmohamedali** 2019-02-01 16:42 UTC
